FROM ubuntu:22.04

RUN apt-get update -y
RUN apt-get install -y build-essential
RUN apt-get install -y cmake
RUN apt-get install -y gdb
RUN apt-get install -y git
RUN apt-get install -y gnuplot
RUN apt-get install -y ninja-build
RUN apt-get install -y vim
RUN apt-get clean -y

RUN git config --global --add safe.directory '*'

RUN mkdir /work_dir

WORKDIR /work_dir

CMD ["/bin/bash", "-l"]
