name: C++ Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install All Dependencies
      run: sudo bash prepare.sh
    - name: Create Build Directory
      run: mkdir build
    - name: Configure CMake
      run: cd build && cmake ..
    - name: Build
      run: cd build && make -j8
    - name: Test
      run: cd build && ctest -j8 --output-on-failure
